name = "dorm-network-check"
account_id = "370e521d89a70d895de8448a36449b93"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dorm_network_check"
database_id = "1a1fca47-6973-42cc-81d6-27735548e7dd"
migrations_dir = "migrations"

[assets]
directory = "public"
binding = "ASSETS"

[vars]
DORM_LAT = "35.844103"
DORM_LNG = "128.625689"
