CREATE TABLE measurements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL,
  lat REAL,
  lng REAL,
  accuracy_m REAL,
  raw_location_tag TEXT NOT NULL,
  is_curfew_window INTEGER NOT NULL,
  location_tag TEXT NOT NULL,
  dong TEXT,
  floor TEXT,
  room TEXT,
  corridor TEXT,
  note TEXT,
  carrier TEXT NOT NULL,
  network_org TEXT,
  os TEXT,
  download_mbps REAL NOT NULL,
  upload_mbps REAL NOT NULL,
  ping_ms REAL NOT NULL,
  jitter_ms REAL NOT NULL,
  packet_loss_pct REAL NOT NULL,
  raw_samples TEXT
);
